// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async modelsDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|models_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cactusModelsDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|cactus_models_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelDownloaded(model: SupportedSttModel) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|is_model_downloaded", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelDownloading(model: SupportedSttModel) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|is_model_downloading", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(model: SupportedSttModel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|download_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(model: SupportedSttModel) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|cancel_download", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(model: SupportedSttModel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|delete_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getServerForModel(model: SupportedSttModel) : Promise<Result<ServerInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|get_server_for_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getServers() : Promise<Result<Partial<{ [key in ServerType]: ServerInfo }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|get_servers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startServer(model: SupportedSttModel) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|start_server", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopServer(serverType: ServerType | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|stop_server", { serverType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSupportedModels() : Promise<Result<SttModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|list_supported_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSpeakerModels() : Promise<Result<SpeakerModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|list_speaker_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isSpeakerModelDownloaded(model: SpeakerModel) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|is_speaker_model_downloaded", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isSpeakerModelDownloading(model: SpeakerModel) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|is_speaker_model_downloading", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadSpeakerModel(model: SpeakerModel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|download_speaker_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelSpeakerDownload(model: SpeakerModel) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|cancel_speaker_download", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSpeakerModel(model: SpeakerModel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|delete_speaker_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isSegmentationModelDownloaded() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|is_segmentation_model_downloaded") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadSegmentationModel() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|download_segmentation_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSegmentationModel() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|delete_segmentation_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSpeakerConfig(enabled: boolean, model: SpeakerModel | null, threshold: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|set_speaker_config", { enabled, model, threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSpeakerConfig() : Promise<Result<[boolean, SpeakerModel | null, number], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|get_speaker_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runBatchSherpa(filePath: string, model: SherpaSttModel, language: string | null, speakerModel: SpeakerModel | null, speakerThreshold: number | null) : Promise<Result<StreamResponse[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:local-stt|run_batch_sherpa", { filePath, model, language, speakerModel, speakerThreshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
downloadProgressPayload: DownloadProgressPayload,
speakerDownloadProgressPayload: SpeakerDownloadProgressPayload
}>({
downloadProgressPayload: "plugin:local-stt:download-progress-payload",
speakerDownloadProgressPayload: "plugin:local-stt:speaker-download-progress-payload"
})

/** user-defined constants **/



/** user-defined types **/

export type AmModel = "am-parakeet-v2" | "am-parakeet-v3" | "am-whisper-large-v3"
export type CactusSttModel = "cactus-whisper-small-int8" | "cactus-whisper-small-int8-apple" | "cactus-whisper-small-int4" | "cactus-whisper-medium-int4" | "cactus-whisper-medium-int4-apple" | "cactus-whisper-medium-int8" | "cactus-whisper-medium-int8-apple" | "cactus-parakeet-ctc-0.6b-int4" | "cactus-parakeet-ctc-0.6b-int8"
export type DownloadProgressPayload = { model: SupportedSttModel; progress: number }
export type ServerInfo = { url: string | null; status: ServerStatus; model: SupportedSttModel | null }
export type ServerStatus = "unreachable" | "loading" | "ready"
export type ServerType = "internal" | "external" | "sherpa"
export type SherpaSttModel = "sherpa-whisper-tiny" | "sherpa-whisper-base" | "sherpa-whisper-small"
export type SpeakerDownloadProgressPayload = { model: SpeakerModel; progress: number }
export type SpeakerModel = "nemo-speakernet" | "3dspeaker-eres2net-base" | "wespeaker-resnet34"
export type SpeakerModelInfo = { key: SpeakerModel; display_name: string; description: string; size_bytes: number }
export type SttModelInfo = { key: SupportedSttModel; display_name: string; description: string; size_bytes: number; model_type: SttModelType }
export type SttModelType = "sherpa" | "cactus" | "whispercpp" | "argmax"
export type SupportedSttModel = SherpaSttModel | CactusSttModel | WhisperModel | AmModel
export type StreamAlternatives = { transcript: string; words: StreamWord[]; confidence: number; languages?: string[] }
export type StreamChannel = { alternatives: StreamAlternatives[] }
export type StreamExtra = { started_unix_millis: number }
export type StreamMetadata = { request_id: string; model_info: StreamModelInfo; model_uuid: string; extra?: StreamExtra }
export type StreamModelInfo = { name: string; version: string; arch: string }
export type StreamResponse = { type: "Results"; start: number; duration: number; is_final: boolean; speech_final: boolean; from_finalize: boolean; channel: StreamChannel; metadata: StreamMetadata; channel_index: number[] } | { type: "Metadata"; request_id: string; created: string; duration: number; channels: number } | { type: "SpeechStarted"; channel: number[]; timestamp: number } | { type: "UtteranceEnd"; channel: number[]; last_word_end: number } | { type: "Error"; error_code: number | null; error_message: string; provider: string }
export type StreamWord = { word: string; start: number; end: number; confidence: number; speaker: number | null; punctuated_word: string | null; language: string | null }
export type WhisperModel = "QuantizedTiny" | "QuantizedTinyEn" | "QuantizedBase" | "QuantizedBaseEn" | "QuantizedSmall" | "QuantizedSmallEn" | "QuantizedLargeTurbo"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
