// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listCalendars() : Promise<Result<CalendarListEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:google-calendar|list_calendars") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEvents(filter: EventFilter) : Promise<Result<CalendarEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:google-calendar|list_events", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AccessRole = "freeBusyReader" | "reader" | "writer" | "owner" | "unknown"
export type AttendeeRole = "chair" | "required" | "optional" | "nonparticipant"
export type AttendeeStatus = "pending" | "accepted" | "tentative" | "declined"
export type CalendarEvent = { provider: CalendarProviderType; 
/**
 * Unique between events. Synthesized for Apple events (eventIdentifier:YYYY-MM-DD for recurring).
 */
id: string; 
/**
 * Calendar id.
 */
calendar_id: string; 
/**
 * iCal identifier used for deduplication.
 * Apple: calendarItemExternalIdentifier, Google: iCalUID.
 */
external_id: string; title: string; description: string | null; location: string | null; url: string | null; 
/**
 * Parsed from notes for Apple, Google provides url directly.
 */
meeting_link: string | null; 
/**
 * ISO 8601. For Google, start of day for all day events (Apple already does that).
 */
started_at: string; 
/**
 * ISO 8601. For Google, end of day for all day events (Apple already does that).
 */
ended_at: string; timezone: string | null; is_all_day: boolean; 
/**
 * Apple: None | Confirmed | Tentative | Canceled -> map None to Confirmed.
 * Google: confirmed | tentative | cancelled.
 */
status: EventStatus; organizer: EventPerson | null; attendees: EventAttendee[]; has_recurrence_rules: boolean; 
/**
 * Google's approach: for an instance of a recurring event, this is the id of the recurring
 * event to which this instance belongs. For Apple, this is the recurrence's series_identifier
 * (same across all occurrences of a recurring event).
 */
recurring_event_id: string | null; 
/**
 * Raw data. JSON for both Apple and Google.
 */
raw: string }
export type CalendarListEntry = { id: string; kind?: string | null; etag?: string | null; summary?: string | null; description?: string | null; location?: string | null; timeZone?: string | null; summaryOverride?: string | null; colorId?: string | null; backgroundColor?: string | null; foregroundColor?: string | null; hidden?: boolean | null; selected?: boolean | null; primary?: boolean | null; deleted?: boolean | null; accessRole?: AccessRole | null; dataOwner?: string | null; defaultReminders?: Reminder[] | null; notificationSettings?: NotificationSettings | null; conferenceProperties?: ConferenceProperties | null; autoAcceptInvitations?: boolean | null }
export type CalendarNotification = { method: NotificationMethod; type: NotificationType }
export type CalendarProviderType = "apple" | "google" | "outlook"
export type ConferenceProperties = { allowedConferenceSolutionTypes?: ConferenceSolutionType[] | null }
export type ConferenceSolutionType = "addOn" | "hangoutsMeet" | "eventNamedHangout" | "eventHangout" | "unknown"
export type EventAttendee = { name: string | null; 
/**
 * Apple calendar events only provide a contact entry, which can possibly not have an email.
 */
email: string | null; 
/**
 * Apple: participant.isCurrentUser, Google: attendee.self.
 */
is_current_user: boolean; 
/**
 * Apple: EKParticipantStatus (Unknown | Pending | Accepted | Declined | Tentative | Delegated | Completed | InProgress).
 * Google: needsAction | declined | tentative | accepted.
 * Normalize: unknown/needsAction -> Pending, delegated/completed/inProgress -> Accepted.
 */
status: AttendeeStatus; 
/**
 * Apple: EKParticipantRole (Unknown | Required | Optional | Chair | NonParticipant).
 * Google: attendee.optional and attendee.organizer.
 * For Apple, normalize unknown as required (see RFC 5545 3.2.16).
 * For Google: organizer -> Chair, !organizer & !optional -> Required, !organizer & optional -> Optional.
 */
role: AttendeeRole }
export type EventFilter = { from: string; to: string; calendar_tracking_id: string }
/**
 * Apple: {name, email, isCurrentUser, ...}, Google: {id, email, displayName, self}.
 */
export type EventPerson = { name: string | null; 
/**
 * Apple calendar events only provide a contact entry, which can possibly not have an email.
 */
email: string | null; 
/**
 * Apple: participant.isCurrentUser, Google: organizer.self.
 */
is_current_user: boolean }
export type EventStatus = "confirmed" | "tentative" | "cancelled"
export type NotificationMethod = "email" | "unknown"
export type NotificationSettings = { notifications?: CalendarNotification[] | null }
export type NotificationType = "eventCreation" | "eventChange" | "eventCancellation" | "eventResponse" | "agenda" | "unknown"
export type Reminder = { method: ReminderMethod; minutes: number }
export type ReminderMethod = "email" | "popup" | "unknown"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
