// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadSessionContent(sessionId: string) : Promise<Result<SessionContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:fs-db|load_session_content", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSessionTranscript(sessionId: string) : Promise<Result<SessionTranscript, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:fs-db|load_session_transcript", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSessionEnhancedNotes(sessionId: string) : Promise<Result<SessionEnhancedNotes, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:fs-db|load_session_enhanced_notes", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSessionContent(sessionId: string, rawMd: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:fs-db|save_session_content", { sessionId, rawMd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSessionTranscript(sessionId: string, transcript: TranscriptData) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:fs-db|save_session_transcript", { sessionId, transcript }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSessionEnhancedNote(sessionId: string, note: EnhancedNoteData, filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:fs-db|save_session_enhanced_note", { sessionId, note, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type EnhancedNoteData = { id: string; sessionId: string; templateId?: string | null; position: number; title?: string | null; content: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type SessionContent = { rawMd: string | null }
export type SessionEnhancedNotes = { notes: EnhancedNoteData[] }
export type SessionTranscript = { transcripts: TranscriptData[] }
export type SpeakerHint = { id: string; wordId: string; type: string; value: JsonValue }
export type TranscriptData = { id: string; userId: string; createdAt: string; sessionId: string; startedAt: number; endedAt?: number | null; words: Word[]; speakerHints: SpeakerHint[] }
export type Word = { id: string; text: string; startMs: number; endMs: number; channel: number; speaker?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
